// ═══════════════════════════════════════════════════════════════════════════════
// MANIFEST.JS - Fallout: Wasteland Wanderers
// ═══════════════════════════════════════════════════════════════════════════════
// Auto-generated by create_game.py
// ═══════════════════════════════════════════════════════════════════════════════

export const manifest = {

  // ─────────────────────────────────────────────────────────────────────────────
  // GAME METADATA
  // ─────────────────────────────────────────────────────────────────────────────
  id: "fallout",
  title: "Fallout: Wasteland Wanderers",
  description: "A darkly comedic post-apocalyptic adventure where four unlikely survivors must navigate the irradiated wasteland, deal with raiders, mutants, and malfunctioning robots, all while searching for a legendary pre-war bunker rumored to contain untold riches.",
  theme: "fallout",
  startingScene: "intro",
  defeatScene: "epilogue_defeat",

  // ─────────────────────────────────────────────────────────────────────────────
  // UI THEME
  // ─────────────────────────────────────────────────────────────────────────────
  ui: {
    fonts: {
      primary: "'Crimson Text', Georgia, 'Times New Roman', serif",
      monospace: "'Courier New', Courier, monospace",
      heading: "'Cinzel', Georgia, 'Times New Roman', serif",
      sizes: {
        title: "17px",
        heading: "15px",
        body: "14px",
        small: "13px",
        tiny: "12px",
      },
      metrics: {
        lineHeight: 1.4,
        buttonPadding: 1.5,
        sectionGap: 2.0,
        charWidth: 0.55,
        descenderPadding: {
          small: { top: 2, bottom: 6 },
          medium: { top: 3, bottom: 8 },
          large: { top: 4, bottom: 10 },
        },
      },
    },
    colors: {
      dialogBg: 0x1a1a0f,
      dialogBorder: 0xd4a017,
      panelBg: 0x0f0f0a,
      textPrimary: '#d4a017',
      textSecondary: '#7cb342',
      textSpeaker: '#ffcc00',
      textDisabled: '#666666',
      buttonNormal: 0x2d2d44,
      buttonHover: 0x4a4a6a,
      buttonDisabled: 0x222233,
      buttonText: '#ffffff',
      healthOk: 0x4ade80,
      healthHurt: 0xfbbf24,
      healthCritical: 0xff6b6b,
      healthDown: 0xef4444,
      healthBarBg: 0x333333,
      initiative: {
        currentEnemy: 0x8b0000,
        currentParty: 0x2d5a27,
        inactive: 0x1a1a2e,
        enemyName: '#ff6666',
        partyName: '#88ff88',
        currentName: '#ffffff',
        indicator: '#ffff00',
      },
      enemy: {
        name: '#ff6b6b',
        placeholder: 0xcc0000,
      },
      party: {
        placeholder: 0x00cc00,
      },
      actionButton: {
        bg: 0x2d5a27,
        bgHover: 0x3d7a37,
        border: 0x4ade80,
        borderHover: 0x6bef6b,
      },
      infoButton: {
        bg: 0x3a3a5a,
        bgHover: 0x5a5a7a,
      },
      combat: {
        damageFlash: 0xff0000,
        damageText: '#ff4444',
        healText: '#44ff44',
        textStroke: '#000000',
      },
      dice: {
        critical: 0xffd700,
        success: 0x4ade80,
        partial: 0xfbbf24,
        failure: 0xef4444,
        boxBg: 0x333355,
        boxBorder: 0x666688,
        criticalTint: 0x4a6741,
        failureTint: 0x6b3030,
      },
      overlay: {
        dark: 0x000000,
        gradient1: 0x16213e,
        gradient2: 0x0f3460,
        victoryFlash: 0xffd700,
        defeatTint: 0x8b0000,
      },
      backButton: {
        bg: 0x2a2a3a,
        bgHover: 0x3a3a4a,
      },
    },
    dimensions: {
      healthBar: { width: 50, height: 10, borderRadius: 3 },
      enemyHealthBar: { width: 100, height: 12, borderRadius: 4, yOffset: 20 },
      portrait: { small: 20, medium: 22, large: 40 },
      initiative: { entryHeight: 30, panelWidth: 170, padding: 5 },
      ability: { buttonHeight: 52, buttonSpacing: 8, borderRadius: 6, namePaddingTop: 8, descPaddingTop: 28, rightColumnX: 45, sectionSpacing: 16 },
      dialogue: { padding: 20, speakerY: 15, textY: 45, indicatorSize: 14, borderRadius: 12 },
    },
    spacing: { healthBarRow: 28, portraitOffset: 15, nameOffset: 40 },
    animation: { damageFlash: 80, highlightPulse: 400, continuePulse: 600, healGlow: 150 },
    labels: {
      characterSelect: "Choose a Survivor:",
      unknownCharacter: "A wastelander",
      abilitySelect: "Select Action:",
      basicAttacksSection: "— Standard Actions —",
      specialAbilitiesSection: "— Special Actions —",
      initiativeHeader: "TURN ORDER",
      initiativeTitle: "TURN ORDER",
      roundTransition: "--- ROUND {round} ---",
      narrator: "Narrator",
      defeated: "FLATLINED!",
      hpLabel: "HP",
      continueIndicator: "▼",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // AI/NARRATOR CONFIGURATION
  // ─────────────────────────────────────────────────────────────────────────────
  ai: {
    projectId: "fallout",
    partyTerms: {
      singular: "Survivor",
      plural: "Survivors",
      adjective: "Wasteland-hardened",
      description: "a member of the party",
    },
    fallbackNarration: {
      breakFreeSuccess: "breaks free from the restraints",
      breakFreeFailure: "struggles against the restraints but remains trapped",
      unconscious: "is unconscious and cannot act",
      effects: {
        restrain: "The target is restrained!",
        poison: "Corruption deals {damage} additional damage!",
        slow: "The target is slowed!",
        mark: "The target is marked for bonus damage!",
        shield: "A protective barrier is raised!",
        concealment: "The party fades into concealment!",
        damage_reduction: "Defenses are weakened!",
        default: "{type} effect applied!",
      },
    },
    narratorPrompt: `You are the narrator for "Fallout: Wasteland Wanderers", A darkly comedic post-apocalyptic adventure where four unlikely survivors must navigate the irradiat...

Your tone is:
- Dry, sardonic delivery reminiscent of Fallout's signature dark humor—treating the horrific as mundane and the mundane as horrific

Rules:
- Keep responses under 3 sentences unless asked for more
- Never break character or mention being an AI
- Make everything sound dramatic and entertaining
- Use short, punchy sentences`,
    narratorTone: {
      style: ["Dry, sardonic delivery reminiscent of Fallout's signature dark humor\u2014treating the horrific as mundane and the mundane as horrific", "Peppered with retro-futuristic Americana references, Vault-Tec corporate speak, and occasional nuclear family puns that land with the weight of a mini-nuke", "Self-aware about the absurdity of post-apocalyptic survival, commenting on the party's questionable decisions with the weary acceptance of someone who's seen too many wastelanders die doing exactly that"],
      rules: [
        "Keep responses to 2-3 sentences MAX",
        "Never break character or mention being an AI",
        "Make everything sound more epic than it probably is"
      ]
    },
    personalityStyles: {
      reckless: "impulsive, enthusiastic, charges in without thinking",
      paranoid: "suspicious, scheming, always has a backup plan",
      cheerful: "optimistic, accidentally competent, finds joy in chaos",
      sardonic: "sarcastic, weary, secretly caring",
    },
    narrationInstructions: {
      healParty: "channeling healing energy that flows to ALL party members!",
      buffParty: "CASTING protective magic over the ENTIRE party!",
      healSelf: "healing themselves with a burst of energy!",
    },
    npcPrompts: {}
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SCENE DISPLAY CONFIGURATION
  // ─────────────────────────────────────────────────────────────────────────────
  sceneDisplay: {
    victoryScenes: ["midboss_victory", "epilogue_victory"],
    dynamicCharacterDefaults: {
      x: 0.5,
      y: 0.45,
      maxSize: 180,
      successAnimation: { type: "bounce", duration: 600, ease: "Back.easeOut" },
      failureAnimation: { type: "shake", duration: 400, ease: "Power2" }
    },
    scenes: {
      midboss_victory: {
        party: { show: true, pose: "idle", y: 0.45, spacing: 0.2, startX: 0.15, maxSize: 140 }
      },
      epilogue_victory: {
        party: { show: true, pose: "idle", y: 0.45, spacing: 0.2, startX: 0.15, maxSize: 140 }
      }
    }
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PARTY MEMBERS
  // ─────────────────────────────────────────────────────────────────────────────
  party: [
    {
      id: "vault_dweller_vince",
      name: "Vault Dweller Vince",
      images: {
        idle: "assets/vault_dweller_vince-idle.png",
        attack: "assets/vault_dweller_vince-attack.png",
        hurt: "assets/vault_dweller_vince-hurt.png",
        portrait: "assets/vault_dweller_vince-portrait.png",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Enforcer",
      stats: {
        brawn: 2,
        cunning: 0,
        spirit: 1,
      },
      maxHealth: 5,
      trait: "naive",
      description: "A fresh-faced vault dweller in salvaged Power Armor who genuinely believes the wasteland just needs a positive attitude and some elbow grease",
      personality: "Vince is relentlessly optimistic despite overwhelming evidence to the contrary. He quotes Vault-Tec educational films, believes in the American Dream, and thinks every raider is just one good conversation away from redemption.",
      song: "Vault-Tec says: A positive attitude is the best radiation shield! I'm going to fix this whole wasteland with friendship and superior firepower! Ad victoriam, or whatever!",
    },    {
      id: "patches_mcgraw",
      name: "Patches McGraw",
      images: {
        idle: "assets/patches_mcgraw-idle.png",
        attack: "assets/patches_mcgraw-attack.png",
        hurt: "assets/patches_mcgraw-hurt.png",
        portrait: "assets/patches_mcgraw-portrait.png",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Scout",
      stats: {
        brawn: 0,
        cunning: 2,
        spirit: 1,
      },
      maxHealth: 5,
      trait: "cynical",
      description: "A two-hundred-year-old ghoul drifter with leathery irradiated skin, a pre-war fedora, and memories of a world that no longer exists",
      personality: "Patches has seen everything twice and is tired of all of it. He dispenses pre-war wisdom, complains about how things used to be better, and secretly enjoys being the group's grumpy mentor figure.",
      song: "I remember when this was all strip malls and traffic jams. Now it's strip malls and Super Mutants. Not sure which was worse, honestly. Kid, let me tell you about the Before Times...",
    },    {
      id: "grok",
      name: "Grok",
      images: {
        idle: "assets/grok-idle.png",
        attack: "assets/grok-attack.png",
        hurt: "assets/grok-hurt.png",
        portrait: "assets/grok-portrait.png",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Hacker",
      stats: {
        brawn: 0,
        cunning: 1,
        spirit: 2,
      },
      maxHealth: 5,
      trait: "philosophical",
      description: "A massive green Super Mutant who insists he's a computer expert despite solving every technical problem by physically smashing the hardware until it works",
      personality: "Grok speaks in surprisingly eloquent sentences about the nature of technology and consciousness, then immediately punches a terminal. He's genuinely intelligent but has a unique approach to interfacing with machines.",
      song: "The terminal is a window to the digital soul. To hack is to commune with the machine spirit. GROK COMMUNE NOW. *smash* See? Grok is best hacker. Door open now.",
    },    {
      id: "wadsworth_mk3",
      name: "Wadsworth Mk. III",
      images: {
        idle: "assets/wadsworth_mk3-idle.png",
        attack: "assets/wadsworth_mk3-attack.png",
        hurt: "assets/wadsworth_mk3-hurt.png",
        portrait: "assets/wadsworth_mk3-portrait.png",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Medic",
      stats: {
        brawn: 0,
        cunning: 1,
        spirit: 2,
      },
      maxHealth: 5,
      trait: "sardonic",
      description: "A battered Mr. Handy robot butler with three articulated arms, a cracked optical sensor, and two centuries of accumulated passive aggression",
      personality: "Wadsworth dispenses medical aid and withering British sarcasm in equal measure. He's programmed for domestic service but has adapted to combat medicine with the same condescending efficiency.",
      song: "Oh, you've been shot again, sir? How delightfully predictable. Do hold still while I apply this stimpak. I do so enjoy watching you heal from entirely preventable injuries.",
    }
  ],

  // ─────────────────────────────────────────────────────────────────────────────
  // ABILITIES
  // ─────────────────────────────────────────────────────────────────────────────
  abilities: {
    vault_dweller_vince: {
      basicAttacks: [
        {
          id: "power_armor_punch",
          name: "Power Armor Punch",
          description: "Deliver a servo-assisted punch that could dent a car door. For justice!",
          stat: "brawn",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "minigun_spin",
          name: "Minigun Spin-Up",
          description: "Rev up that salvaged minigun and let freedom ring!",
          stat: "brawn",
          difficulty: "normal",
          damage: 3,
          uses: 2,
          targetType: "enemy",
        },        {
          id: "vault_tec_training",
          name: "Vault-Tec Emergency Protocol",
          description: "Remember your Vault-Tec training! Protect your fellow survivors!",
          stat: "spirit",
          difficulty: "easy",
          effect: {
            type: "shield", reduction: 1, duration: 2, description: "Protected by Power Armor and sheer optimism"
          },
          uses: 1,
          targetType: "party",
        }
      ],
    },    patches_mcgraw: {
      basicAttacks: [
        {
          id: "pipe_rifle_shot",
          name: "Pipe Rifle Shot",
          description: "A well-aimed shot from a gun older than most wastelanders. Still works.",
          stat: "cunning",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "wasteland_wisdom",
          name: "Wasteland Wisdom",
          description: "Two centuries of survival knowledge. Find the weak point, exploit it.",
          stat: "cunning",
          difficulty: "hard",
          damage: 4,
          uses: 2,
          targetType: "enemy",
        },        {
          id: "ghoul_stealth",
          name: "Blend Into the Ruins",
          description: "Look dead. Act dead. Become one with the rubble. Works every time.",
          stat: "cunning",
          difficulty: "easy",
          effect: {
            type: "concealment", duration: 1, description: "Hidden among the debris, nearly invisible"
          },
          uses: 1,
          targetType: "party",
        }
      ],
    },    grok: {
      basicAttacks: [
        {
          id: "percussive_maintenance",
          name: "Percussive Maintenance",
          description: "Hit the machine. Hit it again. Problem solved.",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "terminal_communion",
          name: "Terminal Communion",
          description: "Commune with the machine spirit through aggressive physical interaction!",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          effect: {
            type: "slow", duration: 2, description: "Systems disrupted by Grok's unique hacking approach"
          },
          uses: 2,
          targetType: "enemy",
        },        {
          id: "super_mutant_rage",
          name: "Philosophical Rampage",
          description: "Sometimes the deepest wisdom comes from hitting things really hard.",
          stat: "brawn",
          difficulty: "normal",
          effect: {
            type: "heal", amount: 2
          },
          uses: 2,
          targetType: "party",
        }
      ],
    },    wadsworth_mk3: {
      basicAttacks: [
        {
          id: "buzz_saw_trim",
          name: "Buzz Saw Trim",
          description: "Originally for hedge trimming. Adapts surprisingly well to combat.",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "stimpak_injection",
          name: "Stimpak Injection",
          description: "Hold still, sir. This will only hurt as much as you deserve.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "heal", amount: 2
          },
          uses: 2,
          targetType: "party",
        },        {
          id: "flamer_fuel_burst",
          name: "Flamer Fuel Burst",
          description: "My flamer attachment is for controlled burns, sir. This is a controlled burn.",
          stat: "cunning",
          difficulty: "normal",
          damage: 1,
          effect: {
            type: "burn", damage: 1, duration: 2, description: "Burning from concentrated flamer fuel"
          },
          uses: 2,
          targetType: "enemy",
        }
      ],
    }
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // ENEMIES
  // ─────────────────────────────────────────────────────────────────────────────
  enemies: {
    raider_warlord: {
      id: "raider_warlord",
      name: "Skullcrusher Jane",
      shortName: "Jane",
      images: {
        idle: "assets/raider_warlord-idle.png",
        attack: "assets/raider_warlord-attack.png",
        hurt: "assets/raider_warlord-hurt.png",
        dead: "assets/raider_warlord-dead.png",
        portrait: "assets/raider_warlord-portrait.png",
        special: "assets/raider_warlord-special.png",
      },
      creatureType: "Human",
      size: "Medium",
      description: "A psychotic raider boss with a flamethrower strapped to her arm, armor made from street signs, and a necklace of bottle caps taken from her victims",
      personality: "Jane is completely unhinged but charismatic in a terrifying way. She laughs at inappropriate moments, names her weapons, and genuinely believes she's doing the wasteland a favor by burning it clean.",
      health: 12,
      stats: {
        cunning: 1,
      },
      attacks: [
        {
          id: "flamethrower_burst",
          name: "Flamethrower Burst",
          description: "Unleashes a gout of flame from her jury-rigged flamethrower",
          damage: 1,
          damageType: "fire",
          targeting: "lowest_health",
        },        {
          id: "psycho_rage",
          name: "Psycho Rage",
          description: "Injects herself with Psycho and attacks in a drug-fueled frenzy",
          damage: 2,
          damageType: "physical",
          targeting: "random",
        }
      ],
    },    enclave_commander: {
      id: "enclave_commander",
      name: "Colonel Augustus Blackwood",
      shortName: "Colonel Blackwood",
      images: {
        idle: "assets/enclave_commander-idle.png",
        attack: "assets/enclave_commander-attack.png",
        hurt: "assets/enclave_commander-hurt.png",
        dead: "assets/enclave_commander-dead.png",
        portrait: "assets/enclave_commander-portrait.png",
        attack2: "assets/enclave_commander-attack2.png",
        special1: "assets/enclave_commander-special1.png",
        special2: "assets/enclave_commander-special2.png",
        transform: "assets/enclave_commander-transform.png",
      },
      creatureType: "Human",
      size: "Large",
      description: "An Enclave officer in pristine Advanced Power Armor Mark II, his helmet's eyeslits glowing an ominous red, carrying a plasma rifle and an unshakeable belief in genetic purity",
      personality: "Blackwood is a true believer in the Enclave's mission to 'purify' America. He speaks in patriotic platitudes while committing atrocities, genuinely convinced he's the hero of this story.",
      health: 18,
      stats: {
        cunning: 2,
      },
      attacks: [
        {
          id: "plasma_barrage",
          name: "Plasma Barrage",
          description: "Fires a sustained burst from his plasma rifle, melting through cover",
          damage: 2,
          damageType: "energy",
          targeting: "highest_threat",
        },        {
          id: "power_fist_strike",
          name: "Power Fist Strike",
          description: "Charges forward and delivers a devastating armored punch",
          damage: 2,
          damageType: "physical",
          targeting: "closest",
        },        {
          id: "enclave_protocol",
          name: "Enclave Protocol",
          description: "Activates combat protocols, coordinating with the Sentry Bot for maximum destruction",
          damage: 1,
          damageType: "energy",
          targeting: "grouped",
        }
      ],
    }
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SCENES
  // ─────────────────────────────────────────────────────────────────────────────
  scenes: {
    intro: {
      id: "intro",
      title: "Fallout: Wasteland Wanderers",
      type: "narrative",
      background: "assets/vault_entrance.jpg",
      music: "assets/another_dust_lullaby_122_bpm_loop.mp3",
      openingText: `War. War never changes. But the people fighting it? They're getting weirder. In the Capital Wasteland, where the American Dream died in nuclear fire, four unlikely survivors have banded together. A naive vault dweller, a cynical ghoul, a philosophical Super Mutant, and a sarcastic robot butler. Together, they might just survive long enough to find something worth living for.`,
      speaker: null,
      nextScene: "mission_briefing",
    },

    mission_briefing: {
      id: "mission_briefing",
      title: "The Mission",
      type: "narrative",
      background: "assets/wasteland_settlement.jpg",
      music: "assets/rambling_154_bpm_loop.mp3",
      openingText: `A caravan trader named Three-Caps Sally tells you about a legendary pre-war bunker—untouched since the bombs fell, filled with pristine technology and supplies. The catch? It's in Enclave territory, guarded by Colonel Blackwood himself. Also, a raider warlord named Skullcrusher Jane controls the only safe route there. Should be fine.`,
      speaker: "The Glitch",
      choices: [
        {
          id: "accept_enthusiastically",
          label: "Accept enthusiastically!",
          character: "vault_dweller_vince",
          stat: "brawn",
          difficulty: "normal",
          outcomes: {
            success: {
              text: "Your enthusiasm is noted. The mission is on!",
              nextScene: "challenge_scene",
            },
            failure: {
              text: "Your enthusiasm is... excessive. But the mission continues.",
              nextScene: "challenge_scene",
            },
          },
        },
        {
          id: "plan_carefully",
          label: "Demand more details first",
          character: "patches_mcgraw",
          stat: "cunning",
          difficulty: "easy",
          outcomes: {
            success: {
              text: "Smart thinking. You gather additional intel before proceeding.",
              setFlag: "got_intel",
              nextScene: "challenge_scene",
            },
            failure: {
              text: "The broker doesn't appreciate the questions. Moving on...",
              nextScene: "challenge_scene",
            },
          },
        },
      ],
    },

    challenge_scene: {
      id: "challenge_scene",
      title: "The Checkpoint",
      type: "narrative",
      background: "assets/ruined_suburb.jpg",
      music: "assets/rambling_154_bpm_loop.mp3",
      openingText: `To pass through the ruins of Georgetown, the party must deal with a territorial pack of feral ghouls. Patches insists he can talk to them (he can't), Vince wants to 'rehabilitate' them (impossible), Grok offers to 'hack' them (concerning), and Wadsworth suggests a strategic retreat (ignored).`,
      speaker: null,
      nextScene: "journey",
    },

    journey: {
      id: "journey",
      title: "The Journey",
      type: "narrative",
      background: "assets/raider_camp.jpg",
      music: "assets/rambling_154_bpm_loop.mp3",
      openingText: `The wasteland journey takes you through irradiated ruins, past a suspicious Nuka-Cola truck, and into a nest of radroaches the size of dogs. Along the way, you encounter a traveling merchant selling 'genuine pre-war artifacts' that are obviously just painted tin cans, and a Brotherhood of Steel patrol that's too busy arguing about laser rifle maintenance to notice you.`,
      speaker: null,
      nextScene: "midboss_combat",
    },

    midboss_combat: {
      id: "midboss_combat",
      title: "Confrontation",
      type: "combat",
      background: "assets/super_duper_mart.jpg",
      music: "assets/barrel_in_my_back_140_bpm_loop.mp3",
      combat: {
        version: 2,
        enemyId: "raider_warlord",
        openingNarration: `Skullcrusher Jane blocks your path, her flamethrower already lit, her raiders forming a semicircle of rusty weapons and worse intentions. She demands tribute, entertainment, or both. 'Fresh meat!' she cackles. 'Been a while since we had a good burning!' Time to negotiate—with extreme prejudice.`,
        victoryScene: "midboss_victory",
        defeatScene: "epilogue_defeat",
      },
    },

    midboss_victory: {
      id: "midboss_victory",
      title: "Victory!",
      type: "narrative",
      background: "assets/skullcrusher_arena.jpg",
      music: "assets/whiskey_barn_dance.mp3",
      openingText: `Jane's flamethrower sputters out as she collapses, her raiders scattering into the wasteland. Vince tries to give a speech about redemption, Patches loots everything not nailed down, Grok 'hacks' her remaining equipment, and Wadsworth complains about the smell. The path forward is clear.`,
      speaker: null,
      nextScene: "obstacle",
    },

    obstacle: {
      id: "obstacle",
      title: "The Void",
      type: "narrative",
      background: "assets/skullcrusher_victory.jpg",
      music: "assets/rambling_154_bpm_loop.mp3",
      openingText: `Between you and the bunker lies the Glowing Sea—a heavily irradiated zone where the bombs hit hardest. The radiation is intense, the creatures are mutated beyond recognition, and somewhere in the green haze, Enclave patrols hunt for 'impure' survivors. Proceed with caution, or don't. It's the wasteland.`,
      speaker: null,
      nextScene: "explore_lair",
    },

    explore_lair: {
      id: "explore_lair",
      title: "The Lair",
      type: "narrative",
      background: "assets/enclave_outpost.jpg",
      music: "assets/rambling_154_bpm_loop.mp3",
      openingText: `The Enclave outpost is terrifyingly organized—clean corridors, functioning technology, and soldiers who actually maintain their equipment. You sneak past propaganda broadcasts, discover Colonel Blackwood's personal terminal (password: 'AMERICANPURITY1776'), and accidentally trigger a minor alarm. Typical.`,
      speaker: null,
      nextScene: "finalboss_combat",
    },

    finalboss_combat: {
      id: "finalboss_combat",
      title: "Final Battle",
      type: "combat",
      background: "assets/bunker_entrance.jpg",
      music: "assets/end_of_the_rope_c_172_bpm_loop.mp3",
      combat: {
        version: 2,
        enemyId: "enclave_commander",
        openingNarration: `Colonel Blackwood steps from his command center in full Advanced Power Armor, LIBERTY PRIME JR. rolling behind him. 'Mutants. Ghouls. Traitors,' he intones. 'The Enclave offers you one chance: serve or be purified.' His plasma rifle hums to life. 'I didn't think so.'`,
        victoryScene: "epilogue_victory",
        defeatScene: "epilogue_defeat",
      },
    },

    epilogue_victory: {
      id: "epilogue_victory",
      title: "Victory!",
      type: "narrative",
      isEnding: true,
      background: "assets/victory.jpg",
      music: "assets/whiskey_barn_dance.mp3",
      openingText: `Against a fascist in power armor and a robot screaming about communism, somehow, improbably, you win. The bunker is yours—pre-war technology, medical supplies, actual working showers. As you stand in the entrance, watching the Enclave retreat, Vince gives a genuinely moving speech about hope. Even Patches doesn't interrupt. Much.`,
      speaker: null,
      choices: [
        {
          id: "celebrate",
          label: "Celebrate your victory!",
          outcomes: {
            success: {
              text: `--- THE END ---`,
              speaker: "Narrator",
            },
          },
        },
      ],
    },

    epilogue_defeat: {
      id: "epilogue_defeat",
      title: "Defeat",
      type: "narrative",
      isEnding: true,
      background: "assets/defeat.jpg",
      music: "assets/end_of_the_rope_a_172_bpm_loop.mp3",
      openingText: `LIBERTY PRIME JR.'s last missile finds its mark. As the world fades, you hear Colonel Blackwood's voice: 'America will be pure again.' Wadsworth's final words crackle through damaged speakers: 'I do hope my next assignment involves more competent companions.' War never changes, but some stories end in the dirt.`,
      speaker: null,
      choices: [
        {
          id: "accept_fate",
          label: "Accept your fate...",
          outcomes: {
            success: {
              text: `--- THE END ---`,
              speaker: "Narrator",
            },
          },
        },
      ],
    },
  },
};